function Eout=Ecase1(Ein, wp_angle_sample, retardance_sample, pol_angle_sample, px_sample, py_sample, analyzer_angles, px_analyzer, py_analyzer)

    Eout = wp_t(wp_angle_sample, retardance_sample) *... 
            linpol_tp(pol_angle_sample, px_sample, py_sample) *... 
            linpol_tp(analyzer_angles, px_analyzer, py_analyzer) *...
            Ein;